# Generated by Django 5.2 on 2025-06-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бренда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('region', models.CharField(choices=[('bishkek', 'Бишкек'), ('osh', 'Ош'), ('jalal-abad', 'Джалал-Абад'), ('karakol', 'Каракол'), ('naryn', 'Нарын'), ('talas', 'Талас'), ('batken', 'Баткен'), ('other', 'Другой')], max_length=50, verbose_name='Регион')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='producer_logos/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код для оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название точки')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Часы работы')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_locations', to='users.producer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Точка продаж',
                'verbose_name_plural': 'Точки продаж',
            },
        ),
    ]
