# Generated by Django 5.2 on 2025-06-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='producer',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Например: 996777123456 (без +)', max_length=20, null=True, verbose_name='WhatsApp номер'),
        ),
    ]
